#!/bin/bash
# Usage: run in home directory or wherever . files are normally located.

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# bash
ln -s ${BASEDIR}/.bash_functions .bash_functions
ln -s ${BASEDIR}/.bashrc .bashrc

# git
ln -s ${BASEDIR}/.git .git
ln -s ${BASEDIR}/.git-completion.sh .git-completion.sh
ln -s ${BASEDIR}/.gitconfig .gitconfig
ln -s ${BASEDIR}/.gitignore_global .gitignore_global

# vim
ln -s ${BASEDIR}/.vim/ .vim
ln -s ${BASEDIR}/.viminfo .viminfo
ln -s ${BASEDIR}/.vimrc .vimrc
